# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for JAM (Japanese Anki Miner)
# Build with: pyinstaller jam.spec
#
# Portable layout (everything next to JAM.exe):
#   JAM.exe
#   data/
#     audio/        ← generated at runtime
#     jmdict.db     ← built on first run via build_db.py
#     mined.db      ← created at runtime
#   settings.json   ← created on first run
#   _internal/      ← PyInstaller runtime + bundled packages

import os
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

block_cipher = None

# ── Project directories ───────────────────────────────────────────────────────
ROOT_DIR = os.path.dirname(os.path.abspath(SPEC))
SRC_DIR  = os.path.join(ROOT_DIR, "src")
DATA_DIR = os.path.join(ROOT_DIR, "data")
ASSETS_DIR = os.path.join(ROOT_DIR, "assets")

print("[PyInstaller] Building JAM from spec...")
print(f"[PyInstaller] ROOT_DIR : {ROOT_DIR}")
print(f"[PyInstaller] SRC_DIR  : {SRC_DIR}")
print(f"[PyInstaller] DATA_DIR : {DATA_DIR}")

# ── Icon ──────────────────────────────────────────────────────────────────────
_icon_path = os.path.join(ASSETS_DIR, "icon.ico")
ICON = _icon_path if os.path.isfile(_icon_path) else None
if ICON:
    print(f"[PyInstaller] Icon      : {ICON}")
else:
    print("[PyInstaller] Icon      : none (add assets/icon.ico to enable)")

# ============================================================================
# DATA FILES
# ============================================================================
datas = []

# 1. External package data (sudachipy, manga_ocr) ─────────────────────────────
print("[PyInstaller] Collecting external package data files...")
sudachi_data  = collect_data_files("sudachipy")
manga_ocr_data = collect_data_files("manga_ocr")
datas += sudachi_data
datas += manga_ocr_data
from PyInstaller.utils.hooks import collect_data_files

print(f"[PyInstaller]   sudachipy  : {len(sudachi_data)} entries")
print(f"[PyInstaller]   manga_ocr  : {len(manga_ocr_data)} entries")

# MangaOCR data files
datas += collect_data_files("manga_ocr")
datas += collect_data_files("transformers")
datas += collect_data_files("huggingface_hub")
datas += collect_data_files("unidic_lite")    # critical — contains dicdir/version
datas += collect_data_files("fugashi")
datas += collect_data_files("google.protobuf")
datas += collect_data_files("timm")           # MangaOCR uses timm for ViT backbone

# Bundle manga_ocr .py source files — transformers reads them at runtime
# via inspect.getfile() in _can_set_experts_implementation()
import manga_ocr as _manga_ocr_mod
import os
_manga_ocr_dir = os.path.dirname(_manga_ocr_mod.__file__)
datas += [(_manga_ocr_dir, "manga_ocr")]

import transformers as _transformers_mod
import os
_transformers_dir = os.path.dirname(_transformers_mod.__file__)

# Only bundle the submodules MangaOCR actually uses
for _subdir in ["models/vision_encoder_decoder", "models/trocr", "models/vit", "models/bert_japanese"]:
    _src = os.path.join(_transformers_dir, _subdir)
    _dst = f"transformers/{_subdir}"
    if os.path.isdir(_src):
        datas += [(_src, _dst)]

# Also bundle modeling_utils.py itself
datas += [(os.path.join(_transformers_dir, "modeling_utils.py"), "transformers")]

# Instead of all of torch data, just collect the essential configs
import torch, os
torch_dir = os.path.dirname(torch.__file__)
datas += [(os.path.join(torch_dir, "share"), "torch/share")]

# 2. data/build_db.py — bundled so the app can build jmdict.db on first run.
#    We copy ONLY the files we explicitly list; never the whole data/ folder,
#    so that local jmdict.db / mined.db / audio/ / raw/ are never baked in.
print("[PyInstaller] Adding data/build_db.py ...")
_build_db = os.path.join(DATA_DIR, "build_db.py")
_data_init = os.path.join(DATA_DIR, "__init__.py")

if os.path.isfile(_build_db):
    # Destination inside the bundle is the 'data' sub-folder (maps to
    # sys._MEIPASS/data at runtime, NOT the user-writable data/ folder).
    datas.append((_build_db, "data"))
    print("[PyInstaller]   Added: data/build_db.py")
else:
    print(f"[PyInstaller]   WARNING: {_build_db} not found — skipping")

if os.path.isfile(_data_init):
    datas.append((_data_init, "data"))
    print("[PyInstaller]   Added: data/__init__.py")

# Files intentionally NOT bundled (created/managed at runtime next to the exe):
#   data/jmdict.db   — built on first launch by build_db.py
#   data/mined.db    — created at runtime
#   data/audio/      — generated by VOICEVOX on demand
#   data/raw/        — source files only needed during dictionary build
#   src/core/settings.json — written at runtime next to the exe

# ============================================================================
# HIDDEN IMPORTS
# ============================================================================
print("[PyInstaller] Setting up hidden imports...")

hiddenimports = [
    # ── External packages ─────────────────────────────────────────────────────
    "sudachipy",
    "sudachidict_full",
    "manga_ocr",
    "PIL",
    "pystray",
    "pynput",
    "aiohttp",
    "lxml",
    "cv2",           # opencv-python

    # Pillow image formats used by MangaOCR
    "PIL.Image",
    "PIL.ImageOps",
    "PIL.JpegImagePlugin",
    "PIL.PngImagePlugin",

    # tkinter — used by notifier.py for all toast windows.
    # PyInstaller does not collect it automatically on Windows; must be explicit.
    "tkinter",
    "tkinter.ttk",
    "_tkinter",

    # ── JAM internal modules ──────────────────────────────────────────────────
    "core.anki",
    "core.audio",
    "core.bbox",
    "core.capture",
    "core.detector",
    "core.dictionary",
    "core.image",
    "core.notifier",
    "core.ocr",
    "core.parser",
    "core.settings",
    "models.audio",
    "models.card",
    "models.word",
    "ui.settings_window",
    "ui.tray",
    "ui.word_selector",

    # MangaOCR + transformers stack
    "manga_ocr",
    "transformers",
    "transformers.models.auto",
    "transformers.models.auto.tokenization_auto",
    "transformers.models.auto.modeling_auto",
    "transformers.models.vision_encoder_decoder",
    "transformers.models.vision_encoder_decoder.modeling_vision_encoder_decoder",
    "transformers.models.bert_japanese",
    "transformers.models.bert_japanese.tokenization_bert_japanese",
    "transformers.models.vit",
    "transformers.models.vit.modeling_vit",
    "transformers.models.trocr",
    "transformers.models.trocr.modeling_trocr",
    "transformers.models.trocr.processing_trocr",

    # HuggingFace hub
    "huggingface_hub",
    "huggingface_hub.file_download",
    "huggingface_hub.utils",

    # Tokenizer backends
    "fugashi",
    "unidic_lite",
    "jaconv",
    "mojimoji",

    # Protobuf
    "google",
    "google.protobuf",
    "google.protobuf.descriptor",
    "google.protobuf.descriptor_pool",
    "google.protobuf.descriptor_pb2",
    "google.protobuf.message",
    "google.protobuf.reflection",
    "google.protobuf.symbol_database",
    "google.protobuf.internal",
    "google.protobuf.internal.decoder",
    "google.protobuf.internal.encoder",

    # Torch internals that get missed
    "torch",
    "torch.nn",
    "torch.nn.functional",
    "torch.utils",
    "torch.utils.data",
    "torch.distributed",
    "unittest",           # torch.distributed pulls this in
    "unittest.mock",

    "timm",
    "timm.models",
    "timm.models.vision_transformer",
    "timm.layers",
]

# pynput discovers its backend modules at runtime via importlib — collect all.
print("[PyInstaller] Collecting pynput submodules...")
_pynput_subs = (
    collect_submodules("pynput")
    + collect_submodules("pynput.keyboard")
    + collect_submodules("pynput.mouse")
)
hiddenimports += _pynput_subs
print(f"[PyInstaller]   Added {len(_pynput_subs)} pynput submodules")

# ============================================================================
# ANALYSIS
# ============================================================================
print("[PyInstaller] Starting Analysis...")
a = Analysis(
    ["src/main.py"],
    pathex=[ROOT_DIR, SRC_DIR],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "test",
    ],
    win_private_assemblies=False,
    win_no_prefer_redirects=False,
    cipher=block_cipher,
    noarchive=False,
)

print("[PyInstaller] Analysis complete")
print(f"[PyInstaller]   Pure Python modules : {len(a.pure)}")
print(f"[PyInstaller]   Binaries            : {len(a.binaries)}")
print(f"[PyInstaller]   Data files          : {len(a.datas)}")

# ============================================================================
# PACKAGING
# ============================================================================
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="JAM",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX corrupts _tkinter.pyd and Tcl/Tk DLLs on Windows
    console=False,      # No console window — system tray app
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,          # None until assets/icon.ico is added
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,          # UPX corrupts _tkinter.pyd and Tcl/Tk DLLs on Windows
    upx_exclude=[],
    name="JAM",
)

print("[PyInstaller] Spec complete — run: pyinstaller jam.spec")
